batch_shipyard:
  storage_account_settings: mystorageaccount
global_resources:
  docker_images:
  - mesnardo/petibm:0.3.1-GPU-IntelMPI-ubuntu
  volumes:
    shared_data_volumes:
      glustervol:
        volume_driver: glusterfs_on_compute
        container_path: $AZ_BATCH_NODE_SHARED_DIR/gfs
        mount_options: []
        bind_options: rw
