remote_fs:
  resource_group: <resource-group>
  location: <location>
  managed_disks:
    premium: true
    disk_size_gb: 63
    disk_names:
    - p6-disk0a
    - p6-disk1a
  storage_clusters:
    mystoragecluster:
      hostname_prefix: snakestoragecluster
      ssh:
        username: shipyard
      public_ip:
        enabled: true
        static: false
      virtual_network:
        name: myvnet
        address_space: 10.0.0.0/16
        existing_ok: true
        subnet:
          name: my-server-subnet
          address_prefix: 10.0.0.0/24
      network_security:
        ssh:
        - '*'
      file_server:
        type: nfs
        mountpoint: /data
        mount_options:
        - noatime
        - nodiratime
        server_options:
          nfs:
            '*':
            - rw
            - async
            - no_root_squash
            - no_subtree_check
      vm_count: 1
      vm_size: STANDARD_F2S
      accelerated_networking: true
      vm_disk_map:
        '0':
          disk_array:
          - p6-disk0a
          - p6-disk1a
          filesystem: btrfs
          raid_level: 0
