remote_fs:
  resource_group: <resource-group>
  location: <location>
  managed_disks:
    premium: true
    disk_size_gb: 31
    disk_names:
    - p4-disk0a
    - p4-disk1a
    - p4-disk0b
    - p4-disk1b
  storage_clusters:
    mystoragecluster:
      hostname_prefix: snakestoragecluster
      ssh:
        username: shipyard
      public_ip:
        enabled: true
        static: false
      virtual_network:
        name: myvnet
        address_space: 10.0.0.0/16
        existing_ok: true
        subnet:
          name: my-server-subnet
          address_prefix: 10.0.0.0/24
      network_security:
        ssh:
        - '*'
      file_server:
        type: glusterfs
        mountpoint: /data
        mount_options:
        - noatime
        - nodiratime
        server_options:
          glusterfs:
            volume_name: gv0
            volume_type: distributed
            transport: tcp
      vm_count: 2
      vm_size: STANDARD_F2S
      accelerated_networking: true
      vm_disk_map:
        '0':
          disk_array:
          - p4-disk0a
          - p4-disk1a
          filesystem: btrfs
          raid_level: 0
        '1':
          disk_array:
          - p4-disk0b
          - p4-disk1b
          filesystem: btrfs
          raid_level: 0
