job_specifications:
- id: job-snake
  auto_complete: true
  max_task_retries: 1
  retention_time: 2.00:00:00
  priority: 0
  allow_run_on_missing_image: false
  remove_container_after_exit: true
  shm_size: 256m
  infiniband: true
  gpu: true
  shared_data_volumes:
  - azurefilevol
  tasks:
  - id: null
    docker_image: mesnardo/petibm:0.3.1-GPU-IntelMPI-ubuntu
    max_wall_time: 0.00:30:00
    multi_instance:
      num_instances: pool_current_dedicated
    entrypoint: null
    command: /mnt/fileshare/snake/run-petibm.sh /mnt/fileshare/snake
