batch_shipyard:
  storage_account_settings: mystorageaccount
global_resources:
  docker_images:
  - mesnardo/petibm:0.3.1-GPU-IntelMPI-ubuntu
  volumes:
    shared_data_volumes:
      mystoragecluster:
        volume_driver: storage_cluster
        container_path: $AZ_BATCH_NODE_SHARED_DIR/mystoragecluster
        mount_options: []
        bind_options: rw
  files:
  - source:
      path: snake
    destination:
      shared_data_volume: mystoragecluster
      relative_destination_path: $AZ_BATCH_NODE_SHARED_DIR/mystoragecluster/snake
      data_transfer:
        method: rsync+ssh
