credentials:
  batch:
    aad:
      directory_id: <tenant-id>
      user: <username>
    account_service_url: <batch-account-endpoint>
    resource_group: <resource-group>
  management:
    aad:
      directory_id: <tenant-id>
      user: <username>
    subscription_id: <subscription-id>
  storage:
    mystorageaccount:
      account: <storage-account-name>
      account_key: <storage-account-key>
