credentials:
  batch:
    aad:
      directory_id: <tenant-id>
      user: <username>
    account_service_url: <account-service-url>
    resource_group: <resource-group>
  management:
    aad:
      directory_id: <tenant-id>
      user: <username>
    subscription_id: <subscription-id>
  storage:
    mystorageaccount:
      account: <account-name>
      account_key: <account-key>
