credentials:
  batch:
    aad:
      endpoint: https://batch.core.windows.net
      directory_id: <tenant-id>
      user: <username>
    account_service_url: https://snakelab.eastus.batch.azure.com
    resource_group: snakebatchrg
  management:
    aad:
      endpoint: https://management.azure.com
      directory_id: <tenant-id>
      user: mesnardo@gwu.edu
    subscription_id: <subscription-id>
  storage:
    mystorageaccount:
      endpoint: core.windows.net
      account: mesnardo2storage
      account_key: <storage-account-key>
